name: Update README with Discord Image

on:
  schedule:
    - cron: "*/10 * * * *" 
  
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        image_url="https://discord.aleu.xyz/user/739673575929282571?v=$(date +%s)"
        sed -i "s|!\[Image\](https://discord.aleu.xyz/user/739673575929282571?v=[^\)]*)|![Image]($image_url)|" README.md

    - name: Commit changes
      run: |
        git config --local user.email "me@alpha0091.xyz"
        git config --local user.name "GitHub Action"
        git commit -am "Update README with latest Discord image"
        git push
